### ISSUE TITLE
power dosnt look right

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVConsumer#12]
**Describe the bug**
plotting the power from pv system '1209',look wrong

![Screenshot 2022-03-17 at 12 04 31](https://user-images.githubusercontent.com/34686298/158804932-f29e1ea4-ec6c-4e3f-8ceb-19cb5256e6fd.png)

**Expected behavior**
smooth plot, looking more like a sun curve

**Comment by JackKelly** [comment]
Is it possible this is a plotting issue? The labels on the `y` axis look kind of strange!

What does the plot look like if a `y` axis is sorted and has tick marks at regular intervals?

**Comment by peterdudfield** [comment]
not an issue, just bad plotting

**Comment by peterdudfield** [comment]
![Uploading Screenshot 2022-03-17 at 12.29.20.png…]()

**Comment by peterdudfield** [comment]
![Screenshot 2022-03-17 at 12 29 20](https://user-images.githubusercontent.com/34686298/158808697-5d8cce8d-db28-4deb-8d1b-8bce3230f5b9.png)

**Comment by peterdudfield** [comment]
> Is it possible this is a plotting issue? The labels on the `y` axis look kind of strange!
> 
> What does the plot look like if a `y` axis is sorted and has tick marks at regular intervals?

the y axis were strings not floats - silly error
