### ISSUE TITLE
Get pv data from Solar Shefield

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVConsumer#30]
Get PV data straight from Solar Sheffield

more details to come

**Comment by peterdudfield** [comment]
Need to change datetimes, as they are not UTC in the database

**Comment by peterdudfield** [comment]
ALl times are UTC

but 36150, 36386, 43629, 60211 in pvoutput.org look a bit dodgy

**Comment by peterdudfield** [comment]
```
update pv_system
set correct_data=false
where pv_system.pv_system_id in (36150, 36386, 43629, 60211)
```

**Comment by JackKelly** [comment]
> they are not UTC in the database

Does that mean the times are not UTC in _our_ database? (Or Sheffield's DB?)

If they're not in UTC, are they stored with an explicit UTC offset? If not, I fear we'll have duplicate "identical" datetimes at one daylight savings transition, and an hour's gap at the other DST transition!

**Comment by peterdudfield** [comment]
Time are UTC in our database. But there was something funny with the pv systems above .They were reporting information from about 30 mins into the future. Of course this is not possible, so there must be something wrong with that system. 

Easy way was to remove them for the moment

**Comment by peterdudfield** [comment]
When pulling the data, we see no systems going over 1kw in the last week. This is a bit odd. 

Pulling all data from 3rd July, the highest yield value was 736 watts. This is was for system ss_id=7759, system_id=35186, which has a installed cpaacity of 3.9 KWp
