### ISSUE TITLE
The tests fail on a clean install

### ISSUE THREAD

**Issue by simlmx** [openclimatefix/PVConsumer#51]
# Description
The tests fail on branch `main` with a clean setup.

# How To Reproduce
1. Clone the code
2. Follow the readme instructions to run the tests

# Investigation
Here are some things making it break:
* Versions are not pinned in `requirements.txt` (in particular the latest version of `pvsite_model` contained breaking changes)
* The tests are calling real prod API it seems, which fail with 401 errors
* The tests fallback on sqlite when not running in postgresql, which adds to the confusion
* This error comes up often when I try to make things work in a hacky way: `Error loading configuration parameter api_key from config file /home/simon/.pvoutput.yml`

# Recommendations
* Pin the versions (using "^=" rules for external repos and "==" for OCF repos). I recommend using poetry because it allows for both defining flexible rules AND a lock file with hard pinned rules.
* Use `testcontainers` instead of `docker-compose` (like we do in other repos) and run tests using `pytest` directly
* Remove references to `sqlite`
* Mock external APIs. If we want to keep tests that use the real API they should be optional tests and not run by default.

CC @peterdudfield

**Comment by peterdudfield** [comment]
Thats bad, sorry about this. I hate it when things are broken like this

**Comment by peterdudfield** [comment]
Let me have a quick look to see what is failling

**Comment by peterdudfield** [comment]
Yea sorry it should have been pinned to a version

**Comment by peterdudfield** [comment]
I solved it, but my feeling is the upgrade due to #52 should also be able to solve it

**Comment by peterdudfield** [comment]
btw ` pvsite_datamodel=0.1.7` should make it work

**Comment by simlmx** [comment]
I don't think I have tried `0.1.7` but `0.1.6` did not work (I must've rounded to the wrong version when trying to find which should work)!

But some tests assume some local environment (a `$HOME/.pvoutput.yml` file) and if I'm not mistaken some call an external API, which is a very bad idea. Also there were some `requests` errors that could be due to change in the `requests` library, I'm not sure.

**Comment by peterdudfield** [comment]
i looked at the last github actions to be successful, and i think ti was `0.1.7`

**Comment by simlmx** [comment]
This was mostly fixed in
#53 
#55

We decided to keep the tests calling external APIs for now, which are still broken but I opened a new ticket just for those: #54
