### ISSUE TITLE
Bring back the "liveapi" tests

### ISSUE THREAD

**Issue by simlmx** [openclimatefix/PVConsumer#54]
# Description

Currently we are skipping the tests marked `liveapi` in the CI because they fail with this error:

```
  def _get_param_from_config_file(param_name, config_filename=CONFIG_FILENAME):
>       with open(config_filename, mode="r") as fh:
E       FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/.pvoutput.yml'
```

# How to reproduce

Remove `-m "not liveapi"` in the workflow and push the code in a new branch.

# Acceptance criteria

`-m "not liveapi"` is removed from the workflow and the CI passes.

**Comment by peterdudfield** [comment]
in #58
