### ISSUE TITLE
Add timezone to data

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVConsumer#8]
## Detailed Description
Need to wait until BST, and see what timezone pvoutput.org data is int

## Context
Good to have Timezone properly defined, rather than guessing

## Possible Implementation
somere in [here](https://github.com/openclimatefix/PVConsumer/blob/main/pvconsumer/app.py#L144),

**Comment by peterdudfield** [comment]
perhaps need this https://pandas.pydata.org/docs/reference/api/pandas.DatetimeIndex.tz_localize.html

**Comment by JackKelly** [comment]
Please see issue #14

**Comment by JackKelly** [comment]
FWIW, this is where we currently convert the timezone of the PVOutput.org data: https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/data_sources/pv/pv_data_source.py#L403-L404

**Comment by peterdudfield** [comment]
> Please see [openclimatefix/pvoutput#14](https://github.com/openclimatefix/pvoutput/issues/14)

good memory @JackKelly

**Comment by peterdudfield** [comment]
this is now complete, we have to tell it which timezone to put ont, and pvoutput repo puts the timezone on

[code](https://github.com/openclimatefix/pvoutput/blob/main/pvoutput/pvoutput.py#L389)
