### ISSUE TITLE
Speed up

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVConsumer#9]
## Detailed Description
Would be good to use some sort of parralization in the code

## Context
good to speed up

**Comment by JackKelly** [comment]
How slow is it? :slightly_smiling_face: 

I'm always a little nervous about using parallelization in production systems, because it's so much harder to debug :slightly_smiling_face:

**Comment by peterdudfield** [comment]
currently takes ~ 2mins to check all 1400 sites, there might be some easier speed ups

**Comment by JackKelly** [comment]
cool beans, sounds good! And, just to check: Does the code only check a PV system if that PV system was checked more than `pv_sample_period` minutes ago? (Which might speed things up by only checking a subset of the PV systems)

**Comment by peterdudfield** [comment]
yep, only checks the system if {now} - {last data} >  {sample period }

**Comment by JackKelly** [comment]
Awesome, thank you!

**Comment by peterdudfield** [comment]
One way to make debuggin easier when paralization, we just make sure all logs go to cloudwatch and also reference what thread its on and then its a bit easier to debug

**Comment by peterdudfield** [comment]
Currently takes ~1 minute 30

**Comment by peterdudfield** [comment]
POssible now an issue as consumer was taking more then 5 mins to run - https://github.com/openclimatefix/nowcasting_infrastructure

**Comment by peterdudfield** [comment]
https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Fecs$252Fconsumer$252Fpv$252F/log-events/streaming$252Fpv-consumer$252Fdba5c8e1e6904f9ab66e82ee2a6b2cd6


Start: 08:31:35

Get last datetime end / start pulling data: 08:41:23

End: 08:42:09

Probably is pulling the latest datetime from the database

**Comment by peterdudfield** [comment]
Deployed anew version using datamodel=0.0.11 which loads all 'last pv yields' at once. The new times are

It took only 5 seconds to get all the pv yields now

**Comment by peterdudfield** [comment]
Its down to about 1 min now, so I think ill close this for the moment
